before_script:
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python - --version 1.0.10 && /root/.poetry/bin/poetry config virtualenvs.create false
  - $HOME/.poetry/bin/poetry install --no-interaction

pages:
  stage: deploy
  image: python:3.7
  script:
    - scripts/update_translations.sh
    - mkdir public
    - $HOME/.poetry/bin/poetry run python scripts/generate.py public/
  artifacts:
    paths:
      - public
  only:
    - website

pages_test:
  stage: deploy
  image: python:3.7
  script:
    - scripts/update_translations.sh
    - mkdir pages
    - TAGUETTE_TEST_LOCALE=y $HOME/.poetry/bin/poetry run python scripts/generate.py pages/
  artifacts:
    paths:
      - pages
  except:
    - website
