stages:
  - test
  - deploy

sqlite3:
  stage: test
  image: python:3.11.0b3
  script:
    - pip install poetry==1.1.12
    - poetry config virtualenvs.create false
    - poetry install --no-interaction
    - scripts/update_translations.sh
    - python -m readme_renderer README.rst >/dev/null
    - python -Wd -m coverage run --branch --source=taguette tests.py -v
    - coverage html
    - coverage report | tail -n 1 | grep -o '\([0-9]\+\(\.[0-9]\+\)\?%\)$'
    - flake8 --ignore=W503,W504 tests.py taguette
    - "! find taguette -name '*.py' -exec grep --color 'raise \\(validate\\.\\)\\?InvalidFormat([^_]' {} +"
  artifacts:
    paths:
      - htmlcov

sqlite3_redis:
  stage: test
  image: python:3.11.0b3
  services:
    - redis:latest
  script:
    - pip install poetry==1.1.12
    - poetry config virtualenvs.create false
    - poetry install --no-interaction
    - scripts/update_translations.sh
    - TAGUETTE_TEST_REDIS=redis://redis:6379 python -Wd tests.py -v

frontend_firefox:
  stage: test
  image: python:3.11.0b3
  script:
    - apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -yy xvfb firefox-esr
    - curl -Lo /tmp/geckodriver.tar.gz https://github.com/mozilla/geckodriver/releases/download/v0.30.0/geckodriver-v0.30.0-linux64.tar.gz
    - tar -zxf /tmp/geckodriver.tar.gz -C /usr/local/bin geckodriver
    - chmod +x /usr/local/bin/geckodriver
    - pip install poetry==1.1.12
    - poetry config virtualenvs.create false
    - poetry install --no-interaction
    - scripts/update_translations.sh
    - TAGUETTE_TEST_WEBDRIVER=firefox xvfb-run python tests.py -v TestSeleniumMultiuser

frontend_chromium:
  stage: test
  image: python:3.11.0b3
  script:
    - apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -yy xvfb chromium-driver
    - pip install poetry==1.1.12
    - poetry config virtualenvs.create false
    - poetry install --no-interaction
    - scripts/update_translations.sh
    - TAGUETTE_TEST_WEBDRIVER=chromium xvfb-run python tests.py -v TestSeleniumMultiuser

frontend_chromium_subdir:
  stage: test
  image: python:3.11.0b3
  script:
    - apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -yy xvfb chromium-driver
    - pip install poetry==1.1.12
    - poetry config virtualenvs.create false
    - poetry install --no-interaction
    - scripts/update_translations.sh
    - TAGUETTE_TEST_WEBDRIVER=chromium TAGUETTE_TEST_BASE_PATH=/base/path xvfb-run python tests.py -v TestSeleniumMultiuser

sqlite3_latest:
  stage: test
  image: python:3.11.0b3
  script:
    - pip install poetry==1.1.12
    - poetry config virtualenvs.create false
    - rm poetry.lock
    - sed -i 's/^python = ".*$/python = "^3.11"/' pyproject.toml
    - poetry install --no-interaction
    - scripts/update_translations.sh
    - python -Wd tests.py -v

postgres:
  stage: test
  image: python:3.11.0b3
  services:
    - postgres:latest
  variables:
    POSTGRES_USER: taguette
    POSTGRES_PASSWORD: taguette
    TAGUETTE_TEST_DB: postgresql://taguette:taguette@postgres/taguette
  script:
    - pip install poetry==1.1.12
    - poetry config virtualenvs.create false
    - poetry install --no-interaction -E postgres
    - scripts/update_translations.sh
    - python -Wd tests.py -v

mariadb:
  stage: test
  image: python:3.11.0b3
  services:
    - mariadb:latest
  variables:
    MYSQL_DATABASE: taguette
    MYSQL_ROOT_PASSWORD: password
    MYSQL_USER: taguette
    MYSQL_PASSWORD: taguette
    TAGUETTE_TEST_DB: mysql+pymysql://taguette:taguette@mariadb/taguette
  script:
    - pip install poetry==1.1.12
    - poetry config virtualenvs.create false
    - poetry install --no-interaction -E mysql
    - scripts/update_translations.sh
    - python -Wd tests.py -v
