before_script:
  - curl -sSL https://install.python-poetry.org | python3 - && /root/.local/bin/poetry config virtualenvs.create false
  - $HOME/.local/bin/poetry install --no-interaction

pages:
  stage: deploy
  image: python:3.10
  script:
    - mkdir public
    - $HOME/.local/bin/poetry run python scripts/generate.py public/
  artifacts:
    paths:
      - public
  only:
    - website

pages_test:
  stage: deploy
  image: python:3.10
  script:
    - mkdir pages
    - TAGUETTE_TEST_LOCALE=y $HOME/.local/bin/poetry run python scripts/generate.py pages/
  artifacts:
    paths:
      - pages
  except:
    - website
