stages:
  - test
  - deploy

sqlite3:
  stage: test
  image: python:3.10
  script:
    - curl -sSL https://install.python-poetry.org | python3 -
    - $HOME/.local/bin/poetry config virtualenvs.create false
    - $HOME/.local/bin/poetry install --no-interaction
    - scripts/update_translations.sh
    - python -m readme_renderer README.rst >/dev/null
    - python -Wd -m coverage run --branch --source=taguette tests.py -v
    - coverage html
    - coverage report | tail -n 1 | grep -o '\([0-9]\+\(\.[0-9]\+\)\?%\)$'
    - flake8 --ignore=W503,W504 tests.py taguette
    - "! find taguette -name '*.py' -exec grep --color 'raise \\(validate\\.\\)\\?InvalidFormat([^_]' {} +"
  artifacts:
    paths:
      - htmlcov
