stages:
  - test
  - deploy

sqlite3:
  stage: test
  image: python:3.10
  script:
    - curl -sSL https://install.python-poetry.org | python3 -
    - $HOME/.local/bin/poetry config virtualenvs.create false
    - $HOME/.local/bin/poetry install --no-interaction
    - scripts/update_translations.sh
    - python -m readme_renderer README.rst >/dev/null
    - flake8 --ignore=W503,W504 tests.py taguette
    - "! find taguette -name '*.py' -exec grep --color 'raise \\(validate\\.\\)\\?InvalidFormat([^_]' {} +"
  artifacts:
    paths:
      - htmlcov

frontend_firefox:
  stage: test
  image: python:3.10
  script:
    - apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -yy xvfb firefox-esr
    - curl -Lo /tmp/geckodriver.tar.gz https://github.com/mozilla/geckodriver/releases/download/v0.30.0/geckodriver-v0.30.0-linux64.tar.gz
    - tar -zxf /tmp/geckodriver.tar.gz -C /usr/local/bin geckodriver
    - chmod +x /usr/local/bin/geckodriver
    - curl -sSL https://install.python-poetry.org | python3 -
    - $HOME/.local/bin/poetry config virtualenvs.create false
    - $HOME/.local/bin/poetry install --no-interaction
    - scripts/update_translations.sh
    - TAGUETTE_TEST_WEBDRIVER=firefox xvfb-run python tests.py -v TestSeleniumMultiuser

frontend_chromium:
  stage: test
  image: python:3.10
  script:
    - apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -yy xvfb chromium-driver
    - curl -sSL https://install.python-poetry.org | python3 -
    - $HOME/.local/bin/poetry config virtualenvs.create false
    - $HOME/.local/bin/poetry install --no-interaction
    - scripts/update_translations.sh
    - TAGUETTE_TEST_WEBDRIVER=chromium xvfb-run python tests.py -v TestSeleniumMultiuser
