stages:
  - test
  - deploy

run_tests:
  stage: test
  image: python:3.6
  script:
    - pip install pipenv
    - pipenv install --deploy -d
    - pipenv run coverage run --source=taguette tests.py
    - pipenv run coverage html
    - pipenv run flake8 --ignore=W504 setup.py tests.py taguette
  artifacts:
    paths:
      - htmlcov
