stages:
  - test
  - deploy

frontend_chromium_redis:
  stage: test
  image: python:3.10
  services:
    - redis:latest
  script:
    - apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -yy xvfb chromium-driver
    - curl -sSL https://install.python-poetry.org | python3 -
    - $HOME/.local/bin/poetry config virtualenvs.create false
    - $HOME/.local/bin/poetry install --no-interaction
    - scripts/update_translations.sh
    - TAGUETTE_TEST_WEBDRIVER=chromium TAGUETTE_TEST_REDIS=redis://redis:6379 xvfb-run python tests.py -v TestSeleniumMultiuser
