stages:
  - test
  - deploy

run_tests:
  stage: test
  image: python:3.6
  script:
    - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python && /root/.poetry/bin/poetry config settings.virtualenvs.create false
    - $HOME/.poetry/bin/poetry install --no-interaction
    - scripts/update_translations.sh
    - python -m readme_renderer README.rst >/dev/null
    - coverage run --source=taguette tests.py
    - coverage html
    - flake8 --ignore=W504 tests.py taguette
    - ! find taguette -name '*.py' -exec grep --color 'raise \(validate\.\)\?InvalidFormat([^_]' {} +
  artifacts:
    paths:
      - htmlcov
