site_name: Taguette
site_author: Vicky and Remi Rampin
site_dir: public
site_url: https://taguette.org
repo_url: https://gitlab.com/remram44/taguette
repo_name: remram44/taguette
edit_uri: edit/website
copyright: Website content CC BY 4.0
markdown_extensions:
  - attr_list
  - md_in_html
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
nav:
  - Home: index.md
  - About: about.md
  - Install: install.md
  - FAQ: faq.md
  - User Guide: help-guide.md
  - Self-hosting: self-host.md
  - Community resources: community.md
theme:
  name: material
  language: en
  logo: img/taguette.png
  favicon: img/favicon.ico
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.follow
    - toc.integrate
  palette:
    primary: deep purple
  font:
    text: Didact Gothic
    code: Free Mono
extra:
  generator: false
