[tool.poetry]
name = "taguette-website"
version = "0.0"
description = "Taguette website generator"

license = "MIT"

authors = ["Remi Rampin <r@remirampin.com>"]

[tool.poetry.dependencies]
python = ">=3.7,<4"
jinja2 = ">=3.1,<3.2"
babel = ">=2.6,<3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
