apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "taguette.fullname" . }}
  labels:
    {{- include "taguette.labels" . | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "taguette.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "taguette.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - server
            - /config.py
            # TODO: Initialize admin password, it crashes if it prompts
            # Possible create admin with useless password, like
            # INSERT INTO users(login, created, hashed_password) VALUES('admin', '2018-10-17 18:50:38', 'pbkdf2:012345678901234567890123456789012$500000$0000000000111111111122222222223333333333444444444455555555556666');
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "taguette.fullname" . }}
                  key: secret_key
            - name: POSTGRES_HOST
              value: {{ include "taguette.postgresServiceName" . }}
            {{- if .Values.postgres.enabled }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "taguette.postgresSecretName" . }}
                  key: postgres_password
            {{- end }}
            {{- range $secret := .Values.additionalSecrets }}
            - name: {{ $secret.envVarName }}
              secretKeyRef:
                name: {{ $secret.secretName }}
                key: {{ $secret.secretKey }}
            {{- end }}
          volumeMounts:
            - name: config
              mountPath: /config.py
              subPath: config.py
          ports:
            - name: http
              containerPort: 7465
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "taguette.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
